
name : Emotion_Detection_CI_CD_Pipeline

on: push

jobs:
  emotion_detection:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

    steps:      

      - name: code checkout
        uses: actions/checkout@v3

      - name: python setup
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
        
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: Load env vars from YAML
        run: |
          python scripts/load_env_from_yaml.py commmon_vars.yaml
      
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}  
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: pipeline run
        run: |
          dvc repro  
      

